"""init

Revision ID: 6bb08d035565
Revises: 
Create Date: 2026-03-10 22:22:31.383039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bb08d035565'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('level', sa.String(length=32), nullable=False),
    sa.Column('group_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type', 'level', 'group_number')
    )
    op.create_table('doc_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_code', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type_code')
    )
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_number', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=64), nullable=False),
    sa.Column('gender', sa.String(length=8), nullable=True),
    sa.Column('birthday', sa.String(length=16), nullable=True),
    sa.Column('birthday_cal', sa.String(length=8), nullable=True),
    sa.Column('legal_name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_number')
    )
    op.create_table('enrollment_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=8), nullable=False),
    sa.Column('event_time', sa.DateTime(), nullable=True),
    sa.Column('operator_id', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.String(length=128), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('student_number_snapshot', sa.String(length=32), nullable=True),
    sa.Column('student_name_snapshot', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enrollments',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('student_id', 'class_id')
    )
    op.create_table('learning_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('academic_year', sa.String(length=16), nullable=False),
    sa.Column('term', sa.String(length=8), nullable=True),
    sa.Column('record_type', sa.String(length=16), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('recorded_by', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('doc_type', sa.String(length=32), nullable=False),
    sa.Column('doc_number', sa.String(length=64), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'doc_type')
    )
    op.create_table('student_operation_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('operator_id', sa.String(length=32), nullable=False),
    sa.Column('operation_time', sa.DateTime(), nullable=True),
    sa.Column('operation_type', sa.String(length=8), nullable=False),
    sa.Column('field_name', sa.String(length=32), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('remark', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_operation_logs')
    op.drop_table('student_documents')
    op.drop_table('learning_records')
    op.drop_table('enrollments')
    op.drop_table('enrollment_logs')
    op.drop_table('students')
    op.drop_table('doc_types')
    op.drop_table('classes')
    # ### end Alembic commands ###
